services:
  express:
    build: .
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
    command: node server.js
        
        
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    
