services:
  db:
    image: mongo:$MONGO_VERSION
    container_name: db
    networks:
      - net_A
    volumes:
      - mongoVolume:/data/db
    ports:
      - "${MONGO_PORT}:27017"
  server:
    container_name: server
    image: tymonjs/lab7zad2:1.0
    ports:
      - "3003:3000"
    networks:
      - net_A
    depends_on:
      db:
        condition: service_started

volumes:
  mongoVolume:

networks:
  net_A:
    external: false
    driver: bridge
    name: net_A