apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o .
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o .
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - node
            - server.js
          envFrom:
            - secretRef:
                name: postgres-secret
          # image: tymonjs/api:latest
          image: api-kub:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 3001
              protocol: TCP
          resources: # <-- ADD THIS SECTION
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always
