apiVersion: v1
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS notes (
      id SERIAL PRIMARY KEY,
      name TEXT,
      note TEXT
    );
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db
  name: db-cm1
