apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - args:
            - node
            - server.js
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: api-env
          image: tymonjs/api-kub:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always
