apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak-data
  name: keycloak-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath 
